require 'csv'

file = "#{Rails.root}/public/data.csv"

interactions = Interaction.published.where(host_id: 2)

CSV.open( file, 'w' ,write_headers: true, headers:[
  "SupraBank id/link", 
  "Assay Type",
  "Technique", 
  "Molecule Name", 
  "Molecule CANO SMILES",
  "Molecule Charge",
  "Molecule h_bond_donor_count",
  "Molecule h_bond_acceptor_count",
  "Molecule tpsa",
  "Molecule ertl_tpsa",
  "Molecule x_log_p",
  "Molecule cheng_xlogp3",
  "Host Name", 
  "Host CANO SMILES",
  "Host Charge",
  "Host h_bond_donor_count",
  "Host h_bond_acceptor_count",
  "Host tpsa",
  "Host ertl_tpsa",
  "Host x_log_p",
  "Host cheng_xlogp3",
  "Indicator Name", 
  "Indicator CANO SMILES",
  "Indicator Charge",
  "Indicator h_bond_donor_count",
  "Indicator h_bond_acceptor_count",
  "Indicator tpsa",
  "Indicator ertl_tpsa",
  "Indicator x_log_p",
  "Indicator cheng_xlogp3",
  "Cofactor Name", 
  "Cofactor CANO SMILES",
  "Cofactor Charge",
  "Cofactor h_bond_donor_count",
  "Cofactor h_bond_acceptor_count",
  "Cofactor tpsa",
  "Cofactor ertl_tpsa",
  "Cofactor x_log_p",
  "Cofactor cheng_xlogp3",
  "Binding constant",
  "DeltaG kJ mol-1",
  "Temperature °C",
  "DeltaH kJ mol-1",	
  "-TDeltaS kJ mol-1",
  "pH",
  "Buffer",
  "Buffer Source of Concentration",
  "Additive_1",
  "Additive_2",
  "Additive_3",	
  "Solvent_1",
  "Solvent_2",
  "Solvent_3",
  "Dataset ID/Link",
  "Dataset DOI",
  "Literature",
  "Lit DOI"
 ]

  ) do |writer|
  interactions.each do |s|
    writer << [
      "https://suprabank.org/interactions/#{s.id}",
      s.assay_type,
      s.technique,
      s.molecule.display_name,
      s.molecule.cano_smiles,
      s.molecule.charge,
      s.molecule.h_bond_donor_count,
      s.molecule.h_bond_acceptor_count,
      s.molecule.tpsa,
      s.molecule.ertl_tpsa,
      s.molecule.x_log_p,
      s.molecule.cheng_xlogp3,
      s.host.display_name,
      s.host.cano_smiles,
      s.host.charge,
      s.host.h_bond_donor_count,
      s.host.h_bond_acceptor_count,
      s.host.tpsa,
      s.host.ertl_tpsa,
      s.host.x_log_p,
      s.host.cheng_xlogp3,
      s.indicator.present? ? s.indicator.display_name : nil,
      s.indicator.present? ? s.indicator.cano_smiles : nil,
      s.indicator.present? ? s.indicator.charge : nil,
      s.indicator.present? ? s.indicator.h_bond_donor_count : nil,
      s.indicator.present? ? s.indicator.h_bond_acceptor_count : nil,
      s.indicator.present? ? s.indicator.tpsa : nil,
      s.indicator.present? ? s.indicator.ertl_tpsa : nil,
      s.indicator.present? ? s.indicator.x_log_p : nil,
      s.indicator.present? ? s.indicator.cheng_xlogp3 : nil,
      s.conjugate.present? ? s.conjugate.display_name : nil,
      s.conjugate.present? ? s.conjugate.cano_smiles : nil,
      s.conjugate.present? ? s.conjugate.charge : nil,
      s.conjugate.present? ? s.conjugate.h_bond_donor_count : nil,
      s.conjugate.present? ? s.conjugate.h_bond_acceptor_count : nil,
      s.conjugate.present? ? s.conjugate.tpsa : nil,
      s.conjugate.present? ? s.conjugate.ertl_tpsa : nil,
      s.conjugate.present? ? s.conjugate.x_log_p : nil,
      s.conjugate.present? ? s.conjugate.cheng_xlogp3 : nil,
      s.binding_constant,
      s.deltaG,
      s.temperature,
      s.itc_deltaH.present? ? s.itc_deltaH : nil,
      s.itc_deltaST.present? ? s.itc_deltaST : nil,
      s.pH.present? ? s.pH : nil,
      s.buffer.present? ? s.buffer.name : nil,
      s.buffer.present? ? s.buffer.sourceofconcentration : nil,
      s.additives.first.present? ? s.additives.first.display_name : nil,
      s.additives.second.present? ? s.additives.second.display_name : nil,
      s.additives.third.present? ? s.additives.third.display_name : nil,
      s.solvents.first.present? ? s.solvents.first.display_name : nil,
      s.solvents.second.present? ? s.solvents.second.display_name : nil,
      s.solvents.third.present? ? s.solvents.third.display_name : nil,
      s.dataset.present? ? "https://suprabank.org/datasets/#{s.dataset.id}" : nil,
      s.dataset.present? ? s.dataset.identifier : nil,
      s.related_identifier.present? ? s.related_identifier.citation : nil,
      s.related_identifier.present? ? s.related_identifier.relatedIdentifier : nil,
      ]
  end
end

File.delete(file)